name: Continuous integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout sources
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      name: Setup .NET Core SDK
    - run: dotnet restore
      name: Install dependencies
    - run: dotnet build -c Release
      name: Build sources
    - run: dotnet test -c Release
      name: Run tests